const $=id=>document.getElementById(id);
const DATA=window.COMMERCE_RADAR_DATA;
const {categories:CATEGORIES,models:MODELS,channels:CHANNELS,stages:STAGES,opportunities:OPPORTUNITIES}=DATA;
const BRL=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const PCT=new Intl.NumberFormat('pt-BR',{style:'percent',maximumFractionDigits:1});
const KEYS={analyses:'tehkne-commerce-radar-v2-analyses',tests:'tehkne-commerce-radar-v2-tests',legacy:'tehkne-commerce-radar-v1'};
const SIGNALS=[['demand','Demanda percebida',3],['visual','Demonstração visual',4],['recurrence','Recorrência/recompra',3],['different','Diferenciação',3],['competition','Concorrência',3],['risk','Risco operacional',2]];
let currentAnalysis=null;
const load=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const save=(key,value)=>{localStorage.setItem(key,JSON.stringify(value));refreshAll()};
const analyses=()=>load(KEYS.analyses,[]),tests=()=>load(KEYS.tests,[]);
const clamp=n=>Math.max(0,Math.min(100,n));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
if(!localStorage.getItem(KEYS.analyses)){const legacy=load(KEYS.legacy,[]);if(legacy.length)localStorage.setItem(KEYS.analyses,JSON.stringify(legacy))}

function populate(){
  $('category').innerHTML=Object.entries(CATEGORIES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
  $('oppCategory').insertAdjacentHTML('beforeend',Object.entries(CATEGORIES).map(([k,v])=>`<option value="${k}">${v}</option>`).join(''));
  $('testChannel').innerHTML=CHANNELS.map(v=>`<option>${v}</option>`).join('');
  $('testStage').innerHTML=STAGES.map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
  SIGNALS.forEach(([id,label,val])=>$('ranges').insertAdjacentHTML('beforeend',`<label class="field"><span class="rangeHead"><span>${label}</span><output id="${id}Out">${val}</output></span><input id="${id}" type="range" min="1" max="5" value="${val}"><small>1 = baixo · 5 = alto</small></label>`));
}
function formInput(){return{product:$('product').value.trim()||'Produto sem nome',category:$('category').value,audience:$('audience').value,cost:+$('cost').value||0,price:+$('price').value||0,capital:+$('capital').value||0,model:$('model').value,...Object.fromEntries(SIGNALS.map(([id])=>[id,+$(id).value]))}}
function channelScores(x,margin){let s={'TikTok Shop':34,'Mercado Livre':38,'Shopee':35,'Instagram + WhatsApp':30,'Loja própria':22};s['TikTok Shop']+=x.visual*8+x.demand*3+(x.price<=180?8:-6)-x.risk*2;s['Mercado Livre']+=x.demand*7+x.competition*2+(x.price>=40?5:0);s.Shopee+=x.visual*4+(x.price<=120?15:-5)+(['casa','beleza','moda','infantil'].includes(x.category)?8:0);s['Instagram + WhatsApp']+=x.different*7+(x.audience!=='b2c'?8:0)+(x.price>=150?10:0);s['Loja própria']+=x.recurrence*8+x.different*7+(margin>=50?8:0)+(x.model==='proprio'?10:0);if(x.model==='afiliado'){s['TikTok Shop']+=6;s.Shopee+=6;s['Loja própria']-=14}if(x.model==='consignado'){s['Instagram + WhatsApp']+=6;s['Mercado Livre']+=5}if(x.audience==='b2b'){s['Instagram + WhatsApp']+=12;s.Shopee-=5}return Object.entries(s).map(([name,score])=>({name,score:Math.round(clamp(score))})).sort((a,b)=>b.score-a.score)}
function calculate(x){const profit=x.price-x.cost,margin=x.price>0?profit/x.price*100:0,marginScore=clamp(margin/65*100),fit=['afiliado','consignado'].includes(x.model)?100:x.cost?clamp(x.capital/Math.max(x.cost*5,1)*100):0,def=((x.recurrence+(6-x.competition)+(6-x.risk))/3)*20;const score=Math.round(clamp((marginScore*.8+fit*.2)*.30+x.demand*20*.25+x.visual*20*.15+x.different*20*.15+def*.15));return{...x,profit,margin,score,minimum:x.cost?x.cost/.55:0,units:x.cost&&!['afiliado','consignado'].includes(x.model)?Math.floor(x.capital/x.cost):0,channels:channelScores(x,margin),label:score>=78?'Forte candidata a teste':score>=62?'Oportunidade promissora':score>=45?'Testar com cautela':'Baixa prioridade agora',decision:score>=78?'Avançar':score>=45?'Validar':'Descartar',created:new Date().toISOString()}}
function preview(){const a=calculate(formInput());$('liveScore').textContent=a.score;$('scoreRing').style.setProperty('--p',a.score+'%');$('liveLabel').textContent=a.label;$('liveText').textContent=a.score>=62?'Há sinais para um teste pequeno e mensurável.':'A ideia precisa melhorar antes de receber investimento.';$('liveMargin').textContent=PCT.format(a.margin/100);$('liveChannel').textContent=a.channels[0].name;$('liveCapital').textContent=['afiliado','consignado'].includes(a.model)?'R$ 0':BRL.format(a.cost*5)}
function warningList(a){const list=[];if(a.margin<35)list.push('Margem estreita: tarifas, frete e devoluções podem eliminar o lucro.');if(a.competition>=4)list.push('Concorrência alta: diferencie por kit, conteúdo, nicho ou serviço.');if(a.risk>=4)list.push('Risco operacional alto: teste garantia, fornecedor e devoluções.');if(a.visual<=2)list.push('Demonstração fraca: use comparação, prova e explicação objetiva.');return list.length?list:['Registre custos reais e não escale antes de repetir vendas lucrativas.']}
function renderAnalysis(a){currentAnalysis=a;$('results').classList.add('show');$('resultScore').textContent=a.score;$('resultLabel').textContent=a.label;$('resultProduct').textContent=a.product;$('resultSummary').textContent=`${CATEGORIES[a.category]} · ${MODELS[a.model]} · melhor canal inicial: ${a.channels[0].name}.`;$('resultVerdict').textContent=a.score>=78?'Valide imediatamente com investimento pequeno.':a.score>=62?'Boa hipótese; confirme com conteúdo e conversão real.':a.score>=45?'Reformule margem, oferta ou diferenciação antes de escalar.':'Preserve caixa e priorize uma hipótese mais forte.';$('margin').textContent=PCT.format(a.margin/100);$('profit').textContent=BRL.format(a.profit);$('minimum').textContent=BRL.format(a.minimum);$('units').textContent=['afiliado','consignado'].includes(a.model)?'Sem estoque':String(a.units);$('channels').innerHTML=a.channels.map((c,i)=>`<div class="channel"><span class="rank">${i+1}</span><div><b>${c.name}</b><small>${i===0?'Canal principal para o primeiro teste':'Canal complementar ou segunda etapa'}</small></div><strong>${c.score}</strong></div>`).join('');$('offer').textContent=a.different>=4?'Solução especializada por público':a.competition>=4?'Kit com benefício claro':'Produto com prova real';$('offerText').textContent=a.visual>=4?'Mostre o problema, o uso e o resultado antes de explicar especificações.':'Reduza o risco percebido com comparação, medidas, garantia e respostas às objeções.';$('hooks').innerHTML=[`O erro que faz você escolher ${a.product.toLowerCase()} do jeito errado`,`Antes de comprar, confira estes 3 pontos`,`Vale a pena? Teste honesto e sem promessa exagerada`,`Versão barata versus versão que realmente funciona`,`Como resolver essa dor de ${CATEGORIES[a.category].toLowerCase()}`].map(h=>`<div class="hook">${esc(h)}</div>`).join('');$('plan').innerHTML=[`Mapear 10 anúncios, avaliações e reclamações.`,`Escolher um anúncio principal e um reserva em ${a.channels[0].name}.`,`Criar conteúdos de problema, comparação e demonstração.`,`Publicar com link rastreável e CTA simples.`,`Registrar alcance, cliques, mensagens e objeções.`,`Reformular o melhor conteúdo e abordar 5 fornecedores.`,`Decidir entre repetir, ajustar ou descartar.`].map(x=>`<li>${esc(x)}</li>`).join('');$('warnings').innerHTML=warningList(a).map(x=>`<div class="hook">${esc(x)}</div>`).join('');$('homeScore').textContent=a.score;$('homeText').textContent=`${a.product}: ${a.label.toLowerCase()}, margem estimada de ${PCT.format(a.margin/100)}.`;$('results').scrollIntoView({behavior:'smooth'})}

function renderNiches(){const groups={};OPPORTUNITIES.forEach(o=>(groups[o.category]??=[]).push(o));$('nicheGrid').innerHTML=Object.entries(groups).map(([cat,items])=>{const avg=Math.round(items.reduce((s,x)=>s+x.score,0)/items.length),min=Math.min(...items.map(x=>x.capital));return`<article class="card niche"><small>${CATEGORIES[cat]}</small><b>${avg}/100</b><span class="muted">${items.length} ideias · a partir de ${BRL.format(min)}</span></article>`}).join('')}
function filteredOpportunities(){const q=$('oppSearch').value.trim().toLowerCase(),cat=$('oppCategory').value,capital=$('oppCapital').value,model=$('oppModel').value,sort=$('oppSort').value;let arr=OPPORTUNITIES.filter(o=>(!q||`${o.name} ${CATEGORIES[o.category]} ${o.problem}`.toLowerCase().includes(q))&&(cat==='all'||o.category===cat)&&(capital==='all'||o.capital<=+capital)&&(model==='all'||o.model===model));arr.sort((a,b)=>sort==='capital'?a.capital-b.capital:sort==='ticket'?b.ticket-a.ticket:sort==='margin'?b.margin-a.margin:b.score-a.score);return arr}
function renderOpportunities(){const arr=filteredOpportunities();$('oppCount').textContent=arr.length;$('oppEmpty').classList.toggle('hide',!!arr.length);$('opportunityGrid').innerHTML=arr.map(o=>`<article class="card opp"><div class="oppTop"><span class="tag ${o.score>=84?'':'blue'}">${o.score}/100</span><span class="chip">${esc(MODELS[o.model])}</span></div><h3>${esc(o.name)}</h3><p>${esc(o.problem)}</p><div class="oppMeta"><div><small>Capital</small><b>${BRL.format(o.capital)}</b></div><div><small>Ticket</small><b>${BRL.format(o.ticket)}</b></div><div><small>Canal</small><b>${esc(o.channel.replace(' + ','/'))}</b></div></div><p><b>Primeiro teste:</b> ${esc(o.test)}</p><div class="oppActions"><button class="btn primary small" data-analyze-opp="${o.id}">Analisar</button><button class="btn small" data-test-opp="${o.id}">Criar teste</button></div></article>`).join('');document.querySelectorAll('[data-analyze-opp]').forEach(b=>b.onclick=()=>prefillOpportunity(b.dataset.analyzeOpp));document.querySelectorAll('[data-test-opp]').forEach(b=>b.onclick=()=>newTestFromOpportunity(b.dataset.testOpp))}
function prefillOpportunity(id){const o=OPPORTUNITIES.find(x=>x.id===id);if(!o)return;const data={product:o.name,category:o.category,audience:o.category==='negocios'?'b2b':'b2c',cost:Math.max(0,Math.round(o.ticket*(1-o.margin/100))),price:o.ticket,capital:o.capital,model:o.model,demand:o.demand,visual:o.visual,recurrence:o.recurrence,different:o.different,competition:o.competition,risk:o.risk};Object.entries(data).forEach(([k,v])=>{if($(k)){$(k).value=v;$(k).dispatchEvent(new Event('input'))}});go('analyze');setTimeout(()=>renderAnalysis(calculate(formInput())),20)}
function openTestModal(test=null){$('testModal').classList.add('open');$('testModalTitle').textContent=test?.id?'Editar teste':'Novo teste';$('testId').value=test?.id||'';$('testProduct').value=test?.product||'';$('testChannel').value=test?.channel||CHANNELS[0];$('testStage').value=test?.stage||'idea';$('testInvestment').value=test?.investment||0;$('testRevenue').value=test?.revenue||0;$('testViews').value=test?.views||0;$('testClicks').value=test?.clicks||0;$('testOrders').value=test?.orders||0;$('testNext').value=test?.next||'';$('testNotes').value=test?.notes||'';$('deleteTest').classList.toggle('hide',!test?.id);setTimeout(()=>$('testProduct').focus(),30)}
function closeTestModal(){$('testModal').classList.remove('open')}
function newTestFromOpportunity(id){const o=OPPORTUNITIES.find(x=>x.id===id);openTestModal({product:o.name,channel:o.channel,stage:'idea',next:o.test})}
function saveTestForm(){const list=tests(),id=$('testId').value||uid(),old=list.find(x=>x.id===id);const item={...old,id,product:$('testProduct').value.trim(),channel:$('testChannel').value,stage:$('testStage').value,investment:+$('testInvestment').value||0,revenue:+$('testRevenue').value||0,views:+$('testViews').value||0,clicks:+$('testClicks').value||0,orders:+$('testOrders').value||0,next:$('testNext').value.trim(),notes:$('testNotes').value.trim(),updated:new Date().toISOString(),created:old?.created||new Date().toISOString()};save(KEYS.tests,[item,...list.filter(x=>x.id!==id)]);closeTestModal();go('experiments')}
function testCard(t){const ctr=t.views?t.clicks/t.views:0,conv=t.clicks?t.orders/t.clicks:0,tag=t.stage==='validated'?'tag':t.stage==='discarded'?'tag red':'tag blue';return`<article class="testCard"><span class="${tag}">${esc(t.channel)}</span><h4>${esc(t.product)}</h4><p>${esc(t.next||'Defina a próxima ação.')}</p><div class="testMetrics"><div><small>CTR</small><b>${PCT.format(ctr)}</b></div><div><small>Conversão</small><b>${PCT.format(conv)}</b></div><div><small>Pedidos</small><b>${t.orders}</b></div></div><div class="testActions"><button class="btn small" data-edit-test="${t.id}">Atualizar</button></div></article>`}
function renderTests(){const list=tests();$('testCount').textContent=list.length;$('testsEmpty').classList.toggle('hide',!!list.length);$('kanban').classList.toggle('hide',!list.length);const active=list.filter(x=>!['validated','discarded'].includes(x.stage)),validated=list.filter(x=>x.stage==='validated'),revenue=list.reduce((s,x)=>s+x.revenue,0),investment=list.reduce((s,x)=>s+x.investment,0);$('testSummary').innerHTML=`<div class="card"><span>Testes ativos</span><b>${active.length}</b></div><div class="card"><span>Validados</span><b>${validated.length}</b></div><div class="card"><span>Receita registrada</span><b>${BRL.format(revenue)}</b></div><div class="card"><span>Saldo bruto</span><b>${BRL.format(revenue-investment)}</b></div>`;$('kanban').innerHTML=STAGES.map(([key,label])=>{const items=list.filter(x=>x.stage===key);return`<section class="column"><div class="columnHead"><b>${label}</b><span>${items.length}</span></div>${items.map(testCard).join('')}</section>`}).join('');document.querySelectorAll('[data-edit-test]').forEach(b=>b.onclick=()=>openTestModal(list.find(x=>x.id===b.dataset.editTest)))}

function renderComparison(){const list=analyses();$('analysisCount').textContent=list.length;$('comparisonEmpty').classList.toggle('hide',!!list.length);$('comparisonTable').classList.toggle('hide',!list.length);if(!list.length){$('comparisonSummary').innerHTML='';return}const best=[...list].sort((a,b)=>b.score-a.score)[0],avg=Math.round(list.reduce((s,x)=>s+x.score,0)/list.length),ok=list.filter(x=>x.score>=62).length,bestMargin=[...list].sort((a,b)=>b.margin-a.margin)[0];$('comparisonSummary').innerHTML=`<div class="card"><span>Melhor oportunidade</span><b>${esc(best.product)}</b></div><div class="card"><span>Score médio</span><b>${avg}/100</b></div><div class="card"><span>Candidatas a teste</span><b>${ok} de ${list.length}</b></div><div class="card"><span>Maior margem</span><b>${esc(bestMargin.product)}</b></div>`;$('analysisRows').innerHTML=list.map(x=>`<tr><td><b>${esc(x.product)}</b><br><small class="muted">${esc(CATEGORIES[x.category]||x.category)}</small></td><td><span class="chip">${x.score}</span></td><td>${PCT.format(x.margin/100)}</td><td>${esc(x.channels[0].name)}</td><td>${esc(MODELS[x.model]||x.model)}</td><td>${esc(x.decision)}</td><td><button class="delete" data-delete-analysis="${x.id}" aria-label="Excluir">×</button></td></tr>`).join('');document.querySelectorAll('[data-delete-analysis]').forEach(b=>b.onclick=()=>save(KEYS.analyses,list.filter(x=>x.id!==b.dataset.deleteAnalysis)))}
function renderDashboard(){const a=analyses(),t=tests(),active=t.filter(x=>!['validated','discarded'].includes(x.stage)),validated=t.filter(x=>x.stage==='validated');$('dashOpp').textContent=OPPORTUNITIES.length;$('dashAnalyses').textContent=a.length;$('dashTests').textContent=active.length;$('dashValidated').textContent=validated.length;const counts=Object.fromEntries(STAGES.map(([k])=>[k,t.filter(x=>x.stage===k).length])),max=Math.max(1,...Object.values(counts));$('dashboardFunnel').innerHTML=STAGES.map(([k,label])=>`<div class="funnelRow"><span>${label}</span><div class="bar"><i style="--w:${Math.round(counts[k]/max*100)}%"></i></div><b>${counts[k]}</b></div>`).join('');let action;if(active.length){const latest=[...active].sort((x,y)=>new Date(y.updated)-new Date(x.updated))[0];action={title:`Continue o teste: ${latest.product}`,text:latest.next||'Atualize métricas e defina a próxima ação.',go:'experiments',label:'Abrir testes'}}else if(a.length){const best=[...a].sort((x,y)=>y.score-x.score)[0];action={title:`Transforme ${best.product} em experimento`,text:`Score ${best.score}/100 e canal recomendado ${best.channels[0].name}.`,go:'compare',label:'Ver comparativo'}}else{action={title:'Escolha uma oportunidade compatível com seu capital.',text:'O sistema mostrará por onde começar sem comprar estoque desnecessário.',go:'opportunities',label:'Explorar agora'}}$('nextAction').innerHTML=`<b>${esc(action.title)}</b><p>${esc(action.text)}</p><button class="btn primary small">${esc(action.label)}</button>`;$('nextAction').querySelector('button').onclick=()=>go(action.go);const bestSignal=a.length?[...a].sort((x,y)=>y.score-x.score)[0]:OPPORTUNITIES[0];$('homeScore').textContent=bestSignal.score;$('homeText').textContent=a.length?`${bestSignal.product}: melhor análise salva até agora.`:`${bestSignal.name}: destaque inicial do catálogo curado.`}
function go(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('on',x.id===view));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('on',x.dataset.view===view));$('title').textContent={home:'Encontre oportunidades melhores',opportunities:'Explore oportunidades',analyze:'Analise uma oportunidade',experiments:'Acompanhe testes reais',compare:'Compare antes de investir',method:'Entenda o método'}[view];$('side').classList.remove('open');if(view==='opportunities')renderOpportunities();if(view==='experiments')renderTests();if(view==='compare')renderComparison();scrollTo({top:0,behavior:'smooth'})}
function refreshAll(){renderComparison();renderTests();renderDashboard();renderOpportunities()}
function csvDownload(filename,rows){const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function jsonBackup(){const data={version:'0.2',exportedAt:new Date().toISOString(),analyses:analyses(),tests:tests()};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='commerce-radar-backup.json';a.click();URL.revokeObjectURL(url)}

populate();renderNiches();
SIGNALS.forEach(([id])=>$(id).oninput=()=>{$(id+'Out').value=$(id).value;preview()});
['product','category','audience','cost','price','capital','model'].forEach(id=>$(id).oninput=preview);
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=e=>{e.preventDefault();go(b.dataset.go)});
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));
$('menu').onclick=()=>$('side').classList.toggle('open');
$('analysisForm').onsubmit=e=>{e.preventDefault();renderAnalysis(calculate(formInput()))};
$('saveAnalysis').onclick=()=>{if(!currentAnalysis)return;save(KEYS.analyses,[{...currentAnalysis,id:uid()},...analyses()]);go('compare')};
$('createTestFromAnalysis').onclick=()=>{if(currentAnalysis)openTestModal({product:currentAnalysis.product,channel:currentAnalysis.channels[0].name,stage:'idea',next:'Executar o plano de validação de 7 dias.'})};
['oppSearch','oppCategory','oppCapital','oppModel','oppSort'].forEach(id=>$(id).oninput=renderOpportunities);
$('randomOpp').onclick=()=>{const arr=filteredOpportunities(),o=arr[Math.floor(Math.random()*arr.length)]||OPPORTUNITIES[0];prefillOpportunity(o.id)};
$('openNewTest').onclick=()=>openTestModal();$('closeTestModal').onclick=closeTestModal;$('testModal').onclick=e=>{if(e.target===$('testModal'))closeTestModal()};$('testForm').onsubmit=e=>{e.preventDefault();saveTestForm()};
$('deleteTest').onclick=()=>{const id=$('testId').value;if(id&&confirm('Excluir este teste?')){save(KEYS.tests,tests().filter(x=>x.id!==id));closeTestModal()}};
$('clearAnalyses').onclick=()=>{if(confirm('Remover todas as análises salvas?'))save(KEYS.analyses,[])};
$('exportAnalyses').onclick=()=>{const list=analyses();if(list.length)csvDownload('commerce-radar-analises.csv',[['Produto','Categoria','Score','Decisão','Margem','Canal','Modelo'],...list.map(x=>[x.product,CATEGORIES[x.category],x.score,x.decision,PCT.format(x.margin/100),x.channels[0].name,MODELS[x.model]])])};
$('exportTests').onclick=()=>{const list=tests();if(list.length)csvDownload('commerce-radar-testes.csv',[['Produto','Canal','Etapa','Investimento','Receita','Visualizações','Cliques','Pedidos','Próxima ação','Aprendizados'],...list.map(x=>[x.product,x.channel,STAGES.find(s=>s[0]===x.stage)?.[1],x.investment,x.revenue,x.views,x.clicks,x.orders,x.next,x.notes])])};
$('backup').onclick=jsonBackup;
refreshAll();preview();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
window.addEventListener('DOMContentLoaded',()=>{if(document.querySelector('script[src="./module-loader.js"]'))return;const script=document.createElement('script');script.src='./module-loader.js';document.body.append(script)},{once:true});