window.COMMERCE_RADAR_DATA={
  categories:{casa:'Casa e organização',negocios:'Pequenos negócios',tecnologia:'Tecnologia',beleza:'Beleza e autocuidado',moda:'Moda e acessórios',pet:'Pet',creator:'Creators',automotivo:'Automotivo',infantil:'Infantil',outros:'Outros'},
  models:{afiliado:'Afiliado',consignado:'Consignação',microestoque:'Microestoque',proprio:'Produto próprio'},
  channels:['TikTok Shop','Mercado Livre','Shopee','Instagram + WhatsApp','Loja própria'],
  stages:[['idea','Ideia'],['research','Pesquisa'],['content','Conteúdo'],['conversion','Conversão'],['validated','Validado'],['discarded','Descartado']],
  opportunities:[
    {id:'photo-kit',name:'Kit para fotografia de produtos',category:'negocios',model:'afiliado',capital:0,ticket:99,margin:38,score:86,channel:'TikTok Shop',demand:4,visual:5,recurrence:3,different:4,competition:4,risk:2,problem:'Melhorar fotos de anúncios sem estúdio profissional.',test:'Criar comparação antes/depois e medir cliques.'},
    {id:'portable-sealer',name:'Seladora portátil de embalagens',category:'negocios',model:'afiliado',capital:0,ticket:49,margin:34,score:81,channel:'TikTok Shop',demand:4,visual:5,recurrence:2,different:3,competition:3,risk:2,problem:'Fechar pequenas embalagens com rapidez.',test:'Demonstrar em três materiais e registrar objeções.'},
    {id:'drawer-organizer',name:'Organizador ajustável de gavetas',category:'casa',model:'microestoque',capital:280,ticket:69,margin:45,score:79,channel:'Shopee',demand:4,visual:5,recurrence:3,different:3,competition:4,risk:2,problem:'Organizar gavetas sem reforma ou móveis novos.',test:'Publicar transformação de cinco minutos.'},
    {id:'cable-organizer',name:'Kit organizador adesivo de cabos',category:'tecnologia',model:'afiliado',capital:0,ticket:39,margin:31,score:78,channel:'Shopee',demand:4,visual:5,recurrence:2,different:3,competition:4,risk:2,problem:'Reduzir cabos soltos em mesas e home office.',test:'Criar conteúdo com três erros de organização da mesa.'},
    {id:'phone-arm',name:'Suporte articulado para celular',category:'creator',model:'afiliado',capital:0,ticket:79,margin:36,score:83,channel:'TikTok Shop',demand:4,visual:5,recurrence:2,different:4,competition:4,risk:2,problem:'Gravar, atender ou trabalhar sem segurar o celular.',test:'Tutorial de gravação solo com enquadramento repetível.'},
    {id:'pet-travel-kit',name:'Kit de passeio e viagem para pets',category:'pet',model:'microestoque',capital:650,ticket:149,margin:47,score:77,channel:'Instagram + WhatsApp',demand:4,visual:4,recurrence:3,different:4,competition:3,risk:2,problem:'Reunir itens essenciais para passeios e viagens.',test:'Montar três versões por porte e captar pré-pedidos.'},
    {id:'car-cleaning-kit',name:'Kit compacto de limpeza automotiva',category:'automotivo',model:'consignado',capital:0,ticket:129,margin:42,score:80,channel:'Mercado Livre',demand:4,visual:5,recurrence:4,different:3,competition:4,risk:2,problem:'Manter o interior do carro limpo com poucos itens.',test:'Comparar resultado em superfícies diferentes.'},
    {id:'home-office-kit',name:'Kit ergonômico para home office',category:'tecnologia',model:'consignado',capital:0,ticket:219,margin:41,score:82,channel:'Instagram + WhatsApp',demand:4,visual:4,recurrence:2,different:4,competition:3,risk:2,problem:'Melhorar conforto e organização da estação de trabalho.',test:'Checklist de ergonomia com oferta em kit.'},
    {id:'label-starter',name:'Kit inicial de etiquetas para pequenos negócios',category:'negocios',model:'microestoque',capital:500,ticket:119,margin:49,score:84,channel:'Instagram + WhatsApp',demand:4,visual:4,recurrence:5,different:4,competition:3,risk:2,problem:'Padronizar produtos e pedidos sem gráfica complexa.',test:'Oferecer amostra digital e três pacotes de reposição.'},
    {id:'desk-riser',name:'Suporte elevado para monitor e notebook',category:'tecnologia',model:'afiliado',capital:0,ticket:139,margin:35,score:74,channel:'Mercado Livre',demand:4,visual:4,recurrence:2,different:3,competition:4,risk:2,problem:'Liberar espaço e elevar a tela.',test:'Mostrar ganho de espaço e medidas reais.'},
    {id:'beauty-organizer',name:'Organizador modular de maquiagem',category:'beleza',model:'microestoque',capital:420,ticket:89,margin:46,score:76,channel:'Shopee',demand:4,visual:5,recurrence:3,different:3,competition:4,risk:2,problem:'Organizar produtos e acelerar a rotina.',test:'Criar vídeos por tamanho de coleção e ambiente.'},
    {id:'curl-kit',name:'Kit de finalização para cabelos cacheados',category:'beleza',model:'consignado',capital:0,ticket:159,margin:44,score:78,channel:'Instagram + WhatsApp',demand:4,visual:5,recurrence:5,different:4,competition:4,risk:3,problem:'Simplificar a rotina com produtos complementares.',test:'Produzir conteúdo educativo sem alegações médicas.'},
    {id:'creator-light',name:'Luz portátil para creators e vendedores',category:'creator',model:'afiliado',capital:0,ticket:119,margin:35,score:82,channel:'TikTok Shop',demand:4,visual:5,recurrence:2,different:3,competition:4,risk:2,problem:'Melhorar iluminação de vídeos e fotos.',test:'Comparar a mesma cena com e sem luz.'},
    {id:'packing-station',name:'Kit de organização para estação de embalagem',category:'negocios',model:'proprio',capital:1800,ticket:349,margin:55,score:85,channel:'Instagram + WhatsApp',demand:4,visual:5,recurrence:4,different:5,competition:2,risk:3,problem:'Reduzir tempo e erros na separação de pedidos.',test:'Fazer diagnóstico gratuito e pré-venda para cinco lojistas.'},
    {id:'kids-travel',name:'Kit de atividades para viagem infantil',category:'infantil',model:'microestoque',capital:750,ticket:129,margin:48,score:75,channel:'Shopee',demand:4,visual:5,recurrence:3,different:4,competition:3,risk:3,problem:'Entreter crianças em deslocamentos sem telas.',test:'Mostrar uso real e faixa etária com segurança.'},
    {id:'closet-dividers',name:'Divisores e identificadores para armário',category:'casa',model:'microestoque',capital:260,ticket:59,margin:47,score:73,channel:'Shopee',demand:3,visual:5,recurrence:3,different:3,competition:4,risk:2,problem:'Encontrar roupas e categorias com facilidade.',test:'Publicar transformação visual em armário pequeno.'},
    {id:'pet-grooming',name:'Kit doméstico de cuidados para pets',category:'pet',model:'consignado',capital:0,ticket:189,margin:43,score:74,channel:'Mercado Livre',demand:4,visual:4,recurrence:4,different:3,competition:4,risk:3,problem:'Manter cuidados básicos entre visitas profissionais.',test:'Criar conteúdo seguro focado em uso e manutenção.'},
    {id:'seller-content-pack',name:'Pacote digital de templates para vendedores',category:'negocios',model:'proprio',capital:0,ticket:79,margin:92,score:88,channel:'Instagram + WhatsApp',demand:4,visual:4,recurrence:4,different:5,competition:3,risk:1,problem:'Criar anúncios e conteúdo com consistência.',test:'Liberar três templates e vender o pacote completo.'},
    {id:'inventory-labels',name:'Sistema simples de identificação de estoque',category:'negocios',model:'proprio',capital:300,ticket:199,margin:68,score:87,channel:'Instagram + WhatsApp',demand:4,visual:4,recurrence:5,different:5,competition:2,risk:2,problem:'Reduzir erros de localização e separação.',test:'Aplicar em um pequeno estoque e medir tempo economizado.'},
    {id:'productivity-planner',name:'Planner digital para operação de e-commerce',category:'negocios',model:'proprio',capital:0,ticket:49,margin:94,score:84,channel:'Instagram + WhatsApp',demand:4,visual:4,recurrence:4,different:4,competition:3,risk:1,problem:'Organizar pesquisa, conteúdo, pedidos e reposição.',test:'Disponibilizar versão gratuita e medir ativação.'}
  ]
};