-- Commerce Radar v0.3.3 — workspace versionado por usuário
-- Alternativa manual: execute todo este arquivo no SQL Editor do Supabase.

create table if not exists public.commerce_radar_workspaces (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  revision bigint not null default 0,
  device_id text,
  sync_reason text
);

alter table public.commerce_radar_workspaces
  add column if not exists revision bigint not null default 0,
  add column if not exists device_id text,
  add column if not exists sync_reason text;

alter table public.commerce_radar_workspaces enable row level security;
revoke all on table public.commerce_radar_workspaces from anon;
revoke insert, update, delete on table public.commerce_radar_workspaces from authenticated;
grant select on table public.commerce_radar_workspaces to authenticated;

drop policy if exists "Users can read own Commerce Radar workspace" on public.commerce_radar_workspaces;
create policy "Users can read own Commerce Radar workspace"
on public.commerce_radar_workspaces for select
to authenticated
using ((select auth.uid()) = user_id);

create table if not exists public.commerce_radar_workspace_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  revision bigint not null,
  payload jsonb not null,
  device_id text,
  sync_reason text,
  created_at timestamptz not null default now(),
  unique (user_id, revision)
);

alter table public.commerce_radar_workspace_versions enable row level security;
revoke all on table public.commerce_radar_workspace_versions from anon;
grant select on table public.commerce_radar_workspace_versions to authenticated;

drop policy if exists "Users can read own Commerce Radar versions" on public.commerce_radar_workspace_versions;
create policy "Users can read own Commerce Radar versions"
on public.commerce_radar_workspace_versions for select
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists commerce_radar_workspace_versions_user_revision_idx
on public.commerce_radar_workspace_versions (user_id, revision desc);

create or replace function public.sync_commerce_radar_workspace(
  expected_revision bigint,
  workspace_payload jsonb,
  source_device text default null,
  reason text default 'manual'
)
returns table (
  status text,
  revision bigint,
  updated_at timestamptz,
  conflict_revision bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := (select auth.uid());
  current_revision bigint;
  next_revision bigint;
  changed_at timestamptz := now();
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if jsonb_typeof(workspace_payload) <> 'object' then
    raise exception 'Workspace payload must be a JSON object';
  end if;

  if pg_column_size(workspace_payload) > 5242880 then
    raise exception 'Workspace payload exceeds 5 MB';
  end if;

  select w.revision
    into current_revision
    from public.commerce_radar_workspaces as w
   where w.user_id = current_user_id
   for update;

  if not found then
    if coalesce(expected_revision, 0) <> 0 then
      return query select 'conflict'::text, 0::bigint, null::timestamptz, 0::bigint;
      return;
    end if;

    next_revision := 1;
    insert into public.commerce_radar_workspaces (
      user_id, payload, revision, device_id, sync_reason, updated_at
    ) values (
      current_user_id, workspace_payload, next_revision,
      left(coalesce(source_device, 'unknown'), 120),
      left(coalesce(reason, 'manual'), 120), changed_at
    );
  else
    if current_revision <> coalesce(expected_revision, 0) then
      return query select 'conflict'::text, current_revision, null::timestamptz, current_revision;
      return;
    end if;

    next_revision := current_revision + 1;
    update public.commerce_radar_workspaces
       set payload = workspace_payload,
           revision = next_revision,
           device_id = left(coalesce(source_device, 'unknown'), 120),
           sync_reason = left(coalesce(reason, 'manual'), 120),
           updated_at = changed_at
     where user_id = current_user_id;
  end if;

  insert into public.commerce_radar_workspace_versions (
    user_id, revision, payload, device_id, sync_reason, created_at
  ) values (
    current_user_id, next_revision, workspace_payload,
    left(coalesce(source_device, 'unknown'), 120),
    left(coalesce(reason, 'manual'), 120), changed_at
  ) on conflict (user_id, revision) do nothing;

  return query select 'ok'::text, next_revision, changed_at, null::bigint;
end;
$$;

revoke all on function public.sync_commerce_radar_workspace(bigint, jsonb, text, text) from public;
revoke all on function public.sync_commerce_radar_workspace(bigint, jsonb, text, text) from anon;
grant execute on function public.sync_commerce_radar_workspace(bigint, jsonb, text, text) to authenticated;
